/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SongList = Song[];

export interface Song {
  unlock?: string | boolean;
  temp_unlock?: boolean;
  extra_exclusive?: boolean;
  removed?: boolean;
  us_locked?: boolean;
  gold_exclusive?: boolean;
  name: string;
  artist: string;
  genre?: string;
  artist_translation: string;
  bpm: string;
  name_translation: string;
  search_hint?: string;
  double: DoublesCharts;
  single: SinglesCharts;
  jacket: string;
  folder?: string;
}
export interface DoublesCharts {
  basic: null | Chart;
  difficult: null | Chart;
  expert: null | Chart;
  challenge: null | Chart;
}
export interface Chart {
  difficulty: string;
  step: string;
  shock: string;
  freeze: string;
  us_locked?: boolean;
  extra_exclusive?: boolean;
  unlock?: boolean;
}
export interface SinglesCharts {
  beginner: null | Chart;
  basic: null | Chart;
  difficult: null | Chart;
  expert: null | Chart;
  challenge: null | Chart;
}
